# Generated by Django 3.1.13 on 2021-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retag',
            fields=[
                ('cdi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=50, null=True)),
                ('metadata_type', models.CharField(max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
        ),
    ]
