# Generated by Django 3.1.13 on 2021-10-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAPInstance',
            fields=[
                ('cap_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('masterlist_count', models.IntegerField()),
                ('climate_collection_count', models.IntegerField()),
                ('broken_urls', models.IntegerField()),
                ('lost_climate_tag', models.IntegerField()),
                ('not_in_masterlist', models.IntegerField()),
                ('total_warnings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('cdi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50)),
                ('catalog_url', models.URLField()),
                ('api_url', models.URLField()),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('datagov_ID', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retag',
            fields=[
                ('retag_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_id', models.ForeignKey(db_column='cap_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.capinstance')),
                ('datagov_ID', models.ForeignKey(db_column='datagov_ID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.masterlist', to_field='datagov_ID')),
            ],
        ),
        migrations.CreateModel(
            name='QAUpdates',
            fields=[
                ('qa_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog_url', models.URLField(blank=True, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cap_id', models.ForeignKey(db_column='cap_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.capinstance')),
                ('datagov_ID', models.ForeignKey(db_column='datagov_ID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.masterlist', to_field='datagov_ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotInMasterlist',
            fields=[
                ('nml_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('api_url', models.URLField()),
                ('catalog_url', models.URLField()),
                ('cap_id', models.ForeignKey(db_column='cap_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.capinstance')),
            ],
        ),
        migrations.CreateModel(
            name='BrokenAPI',
            fields=[
                ('broken_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_id', models.ForeignKey(db_column='cap_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.capinstance')),
                ('datagov_ID', models.ForeignKey(db_column='datagov_ID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.masterlist', to_field='datagov_ID')),
            ],
        ),
    ]
