# Generated by Django 3.1.13 on 2021-10-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broken_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cdi_metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('masterlist_count', models.IntegerField()),
                ('climate_collection_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='not_in_masterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('api_url', models.URLField(null=True)),
                ('catalog_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='original_masterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='qa_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('datagov_id', models.UUIDField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='retag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='updates_masterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='warnings_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.CharField(max_length=20, null=True)),
                ('total_warnings', models.IntegerField()),
                ('broken_urls', models.IntegerField()),
                ('lost_climate_tag', models.IntegerField()),
                ('not_in_masterlist', models.IntegerField()),
            ],
        ),
    ]
