# Generated by Django 3.1.13 on 2021-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDI_dataset',
            fields=[
                ('date_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cdi_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(max_length=50, null=True)),
                ('catalog_url', models.URLField(null=True)),
                ('api_url', models.URLField(null=True)),
                ('cdi_themes', models.CharField(max_length=200, null=True)),
                ('metadata_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geoplatform_id', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('datagov_ID', models.UUIDField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Retag',
        ),
    ]
