# Generated by Django 3.1.13 on 2022-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='api_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='catalog_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='cdi_themes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='metadata_type',
            field=models.CharField(blank=True, choices=[('No metadata type', 'No Metadata Type'), ('geospatial', 'Geospatial')], default='No metadata type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='notinmasterlist',
            name='api_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notinmasterlist',
            name='catalog_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qaupdates',
            name='catalog_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='qaupdates',
            name='metadata_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qaupdates',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='qaupdates',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qaupdates',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
