# Generated by Django 3.1.13 on 2021-10-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211024_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='api_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='catalog_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notinmasterlist',
            name='api_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notinmasterlist',
            name='catalog_url',
            field=models.URLField(max_length=500),
        ),
    ]
