# Generated by Django 3.1.13 on 2021-11-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211024_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='status',
            field=models.CharField(choices=[(0, 'Active'), (1, 'Not Active'), (2, 'Retired')], default=0, max_length=20),
        ),
    ]
