# Generated by Django 3.1.13 on 2021-11-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211102_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Retired', 'Retired')], default=0, max_length=20),
        ),
    ]
