# Generated by Django 3.1.13 on 2021-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211102_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='metadata_type',
            field=models.CharField(blank=True, choices=[('No metadata type', 'No metadata type'), ('geospatial', 'geospatial')], default='No metadata type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active'), ('Retired', 'Retired')], default='Active', max_length=20),
        ),
    ]
