# Generated by Django 3.1.13 on 2021-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211102_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlist',
            name='metadata_type',
            field=models.CharField(blank=True, choices=[('No metadata type', 'No Metadata Type'), ('geospatial', 'Geospatial')], default='No metadata type', max_length=50, null=True),
        ),
    ]
