# Generated by Django 3.1.13 on 2021-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211116_0248'),
        ('dashboard', '0009_auto_20211116_1121'),
    ]

    operations = [
    ]
